import type { VastuRule, ZoneActivationInfo } from "./vastuTypes.js";

export const VASTU_RULES: VastuRule[] = [
  {
    id: "entrance_primary",
    object: "main_entrance",
    objectLabel: "Main Entrance / Main Door",
    idealZones: ["N3", "N4", "E3", "E4", "S3", "S4", "W3", "W4"],
    beneficialZones: ["W5", "N5", "E5"],
    remedyZones: ["S1", "S2", "E1", "E2"],
    remedyDescription: "With brass/copper/aluminum tape on floor",
    strictNoZones: ["SW", "SSW", "WNW", "ESE", "S7", "S8"],
    room: "entrance",
    severity: "critical",
    problem: "Main entrance in inauspicious zone blocks prosperity and positive energy flow",
    scientificReason:
      "Entrance direction determines solar energy intake — East/North entrances receive morning sun (positive ions), South/SW entrances receive afternoon heat causing stress and financial instability",
    traditionalReason:
      "Per Vastu Purush Mandala, SW is governed by Nairutya (demon energy), WNW by Roga (disease deity) — main door here invites negative cosmic forces",
    remedy: {
      easy: "Place brass Swastik or Om symbol on door frame. Use brass/copper threshold strip.",
      moderate: "Hang brass bell above door. Place Ashoka tree or Tulsi plant near entrance.",
      color: "Use green, white, or wood color for door. Avoid red, black, grey.",
      element: "wood",
      plants: "Tulsi, Ashoka, or money plant at entrance",
      crystals: "Clear quartz or green aventurine near entrance",
    },
    expectedImprovement: "Improves financial flow, career opportunities, and family harmony",
    confidenceScore: 95,
  },
  {
    id: "master_bedroom_primary",
    object: "master_bedroom",
    objectLabel: "Master Bedroom",
    idealZones: ["SW"],
    beneficialZones: ["South", "W", "NW"],
    remedyZones: [],
    strictNoZones: ["NE", "ESE", "SSW", "WNW"],
    room: "bedroom",
    severity: "critical",
    problem:
      "Master bedroom in wrong zone causes relationship issues, health problems, and financial instability for head of family",
    scientificReason:
      "SW zone has maximum earth element stability — heavy mass in SW keeps the house grounded. NE is water/clarity zone, not suitable for sleep as it causes restlessness",
    traditionalReason:
      "SW is Pitra/Dauvarik zone governed by ancestors — master bedroom here ensures family head has authority and stability",
    remedy: {
      easy: "Paint SW wall in earthy tones (brown, beige, cream). Place heavy furniture in SW corner.",
      moderate: "Move bed to SW corner of room. Head while sleeping should face South or East.",
      color: "Use earthy tones: brown, beige, cream, light yellow. Avoid blue, black in bedroom.",
      element: "earth",
      plants: "Lavender or jasmine (calming) — avoid cactus or thorny plants",
      crystals: "Rose quartz for relationships, amethyst for peaceful sleep",
    },
    expectedImprovement: "Improves relationship harmony, financial stability, and health of head of family",
    confidenceScore: 93,
  },
  {
    id: "kitchen_primary",
    object: "kitchen",
    objectLabel: "Kitchen / Cooking Hob",
    idealZones: ["SE", "SSE"],
    beneficialZones: ["South"],
    remedyZones: ["NW", "W"],
    remedyDescription: "With Yellow stone slab under hob",
    strictNoZones: ["NE", "North", "SW", "SSW"],
    room: "kitchen",
    severity: "critical",
    problem: "Kitchen/hob in wrong direction causes health issues, financial drain, and relationship conflicts",
    scientificReason:
      "SE is the zone of fire element (Agni) — cooking here aligns with natural fire energy direction. Kitchen in NE (water zone) creates fire-water conflict causing digestive issues and financial loss",
    traditionalReason:
      "SE is governed by Anil/Vitatha deities associated with fire and digestion. NE is Shikhi/Parjanya zone — fire here destroys clarity and causes confusion",
    remedy: {
      easy: "Place a red or orange mat under the cooking platform. Keep a copper vessel near stove.",
      moderate: "If shifting not possible, place yellow stone slab under hob. Add red accent near stove.",
      color: "Use yellow, orange, or red accents in kitchen. Avoid blue or black near stove.",
      element: "fire",
      plants: "Avoid plants near stove. Place basil/tulsi away from cooking zone.",
      crystals: "Carnelian or red jasper near cooking area",
    },
    expectedImprovement: "Improves health, digestion, financial stability, and family relationships",
    confidenceScore: 97,
  },
  {
    id: "toilet_primary",
    object: "toilet",
    objectLabel: "Toilet / Bathroom / Commode",
    idealZones: ["SSW", "WNW", "ESE"],
    beneficialZones: [],
    remedyZones: ["NW", "SE", "East"],
    remedyDescription: "With specific color tapes on floor",
    strictNoZones: ["NE", "SW", "North", "West"],
    room: "bathroom",
    severity: "critical",
    problem: "Toilet in NE causes severe mental confusion, health deterioration, and financial blockage",
    scientificReason:
      "NE receives maximum cosmic radiation in morning — toilet here pollutes the most spiritually active zone. SW toilet drains earth energy causing instability",
    traditionalReason:
      "NE is Ishanya zone — the most sacred corner governed by Lord Shiva. Toilet here is the gravest Vastu defect",
    remedy: {
      easy: "Keep NE toilet door always closed. Place sea salt bowl inside. Change tiles to white/light blue.",
      moderate: "Hang a mirror on outer NE wall to reflect energy outward. Place crystal pyramid inside.",
      color: "White, light blue, or cream tiles. Avoid dark colors in bathroom.",
      element: "water",
      plants: "No plants in bathroom",
      crystals: "Black tourmaline to absorb negative energy",
    },
    expectedImprovement: "Reduces health issues, mental clarity improves, financial blockages reduce",
    confidenceScore: 96,
  },
  {
    id: "washing_machine_primary",
    object: "washing_machine",
    objectLabel: "Washing Machine",
    idealZones: ["WNW", "ESE"],
    beneficialZones: ["NW"],
    remedyZones: ["SSW"],
    remedyDescription: "If kept spotlessly clean",
    strictNoZones: ["NE", "SW", "SE", "North"],
    room: "utility",
    severity: "medium",
    problem: "Washing machine in wrong zone creates water-element conflicts and financial turbulence",
    scientificReason:
      "WNW and ESE zones are neutral zones suitable for utility appliances with water and movement",
    traditionalReason:
      "Washing machine represents Vayu (air/movement) + Jal (water) — WNW is governed by Vayu energy making it ideal",
    remedy: {
      easy: "Place a blue mat under washing machine. Keep area clean and dry.",
      moderate: "Move to NW or WNW if possible.",
      color: "White or light blue for utility area walls",
      element: "water",
      plants: "None required",
      crystals: "None specific",
    },
    expectedImprovement: "Reduces financial turbulence and improves water-related luck",
    confidenceScore: 78,
  },
  {
    id: "dustbin_primary",
    object: "dustbin",
    objectLabel: "Dustbin / Waste Bin",
    idealZones: [],
    beneficialZones: [],
    remedyZones: ["NE", "North", "SW", "SE"],
    remedyDescription: "Always keep covered and empty regularly",
    strictNoZones: [],
    room: "any",
    severity: "low",
    problem: "Dustbin in wrong location attracts negative energy and blocks prosperity",
    scientificReason:
      "Waste accumulation creates bacterial growth and negative environmental energy regardless of direction",
    traditionalReason:
      "Dustbin represents decay (Nirrti energy) — keeping it covered and in SSW or WNW zones is preferred",
    remedy: {
      easy: "Always keep dustbin covered with lid. Empty daily. Keep near SSW or WNW ideally.",
      moderate: "Use a closed cabinet for dustbin storage.",
      color: "Use grey or black bin — avoid bright colors for dustbin",
      element: "earth",
      plants: "None",
      crystals: "None",
    },
    expectedImprovement: "Reduces negative energy accumulation in living spaces",
    confidenceScore: 70,
  },
  {
    id: "medicine_primary",
    object: "medicine_box",
    objectLabel: "Medicine Box / First Aid",
    idealZones: ["NNE"],
    beneficialZones: ["North"],
    remedyZones: ["WNW"],
    remedyDescription: "Specific for detoxing chronic disease",
    strictNoZones: ["SSW", "South", "SW"],
    room: "any",
    severity: "medium",
    problem: "Medicine in wrong zone reduces healing efficiency and prolongs illness",
    scientificReason:
      "NNE is governed by Aditi/Diti deities associated with immunity and healing. North zone has optimal magnetic north alignment supporting healing",
    traditionalReason:
      "NNE is the zone of Dhanvantari (Ayurvedic deity) — medicines here receive maximum healing cosmic energy",
    remedy: {
      easy: "Move medicine box to North or NNE wall. Use white or blue colored medicine box.",
      moderate: "Place Dhanvantari image near medicine storage.",
      color: "White, blue, or light green for medicine storage area",
      element: "water",
      plants: "Tulsi plant nearby supports healing",
      crystals: "Lapis lazuli or aquamarine for healing support",
    },
    expectedImprovement: "Faster recovery from illness, improved immunity, better health outcomes",
    confidenceScore: 82,
  },
  {
    id: "temple_primary",
    object: "temple",
    objectLabel: "Temple / Pooja Room / Mandir",
    idealZones: ["NE", "West"],
    beneficialZones: ["East"],
    remedyZones: [],
    strictNoZones: ["SSW", "WNW", "SW", "sharing_toilet_wall"],
    room: "puja_room",
    severity: "critical",
    problem: "Temple in wrong zone reduces spiritual energy, blocks prayers, and creates negative vibrations",
    scientificReason:
      "NE receives maximum morning sun and cosmic radiation — ideal for meditation and prayer. Sharing wall with toilet creates contamination of sacred space",
    traditionalReason:
      "NE is Ishanya zone governed by Lord Shiva/Brahma — the most sacred corner of any property",
    remedy: {
      easy: "Ensure temple faces East or North. Keep area clean, well-lit, and fragrant.",
      moderate: "If temple is on toilet wall, place thick lead sheet between walls.",
      color: "White, cream, or light yellow for puja room. Avoid dark colors.",
      element: "space",
      plants: "Tulsi, flowers, and fragrant plants near temple",
      crystals: "Clear quartz and amethyst for spiritual amplification",
    },
    expectedImprovement: "Enhanced spiritual practice, prayers answered faster, positive divine energy in home",
    confidenceScore: 94,
  },
  {
    id: "safe_primary",
    object: "safe",
    objectLabel: "Safe / Cash Locker / Valuables",
    idealZones: ["North", "West"],
    beneficialZones: ["SE"],
    remedyZones: ["SW"],
    remedyDescription: "For long-term capital retention",
    strictNoZones: [],
    room: "bedroom",
    severity: "high",
    problem: "Safe in wrong direction causes financial loss and wealth drainage",
    scientificReason:
      "North is magnetic north — facing North maximizes positive ionic flow toward valuables. Kuber (wealth deity) faces North",
    traditionalReason:
      "North is Kubera zone — god of wealth. Safe facing North ensures Kubera blesses the wealth stored",
    remedy: {
      easy: "Ensure safe door opens toward North. Place Kuber yantra on or near safe.",
      moderate: "Move safe to North wall of SW room for maximum retention.",
      color: "Green or gold for safe exterior. Place green cloth inside safe.",
      element: "metal",
      plants: "Money plant near safe area",
      crystals: "Citrine (wealth crystal) inside safe",
    },
    expectedImprovement: "Wealth accumulation improves, financial stability increases, unexpected expenses reduce",
    confidenceScore: 88,
  },
  {
    id: "inverter_primary",
    object: "inverter",
    objectLabel: "Inverter / Heater / Electrical Equipment",
    idealZones: ["SE", "SSE"],
    beneficialZones: [],
    remedyZones: [],
    strictNoZones: ["NE", "North", "SW"],
    room: "any",
    severity: "medium",
    problem: "Electrical/fire equipment in water zones causes health issues and electrical problems",
    scientificReason:
      "SE zone is fire element zone — electrical equipment generates heat/fire energy which is amplified positively in SE",
    traditionalReason: "SE is Agni (fire deity) zone — all fire and electrical appliances belong here",
    remedy: {
      easy: "Move inverter/heater to SE corner if possible. Keep area ventilated.",
      moderate: "Place red mat under electrical equipment in non-SE zones.",
      color: "Red or orange accents near electrical zone",
      element: "fire",
      plants: "None near electrical equipment",
      crystals: "None specific",
    },
    expectedImprovement: "Reduces electrical issues, health improvement, energy efficiency",
    confidenceScore: 80,
  },
  {
    id: "study_table_primary",
    object: "study_table",
    objectLabel: "Study Table / Work Desk / Office Desk",
    idealZones: ["WSW", "NE"],
    beneficialZones: ["East", "West"],
    remedyZones: [],
    strictNoZones: [],
    room: "study",
    severity: "medium",
    problem: "Study desk facing wrong direction reduces concentration, memory, and academic performance",
    scientificReason:
      "East-facing study gets morning sun which activates pineal gland improving alertness. North-facing study aligns with magnetic north improving memory and focus",
    traditionalReason:
      "WSW is Vastu zone of knowledge (Vithi/Gandharva). NE is clarity zone — students studying here gain exceptional focus",
    remedy: {
      easy: "Face East or North while studying. Place Saraswati image or green plant on desk.",
      moderate: "Move desk to NE or WSW corner of room.",
      color: "Green or light blue for study room — enhances concentration",
      element: "wood",
      plants: "Money plant or bamboo for growth energy",
      crystals: "Fluorite for concentration, clear quartz for clarity",
    },
    expectedImprovement: "Improved concentration, better academic results, enhanced career growth",
    confidenceScore: 85,
  },
  {
    id: "dining_table_primary",
    object: "dining_table",
    objectLabel: "Dining Table",
    idealZones: ["West", "East"],
    beneficialZones: ["NW", "South"],
    remedyZones: [],
    strictNoZones: ["SE", "SSW", "WNW"],
    room: "dining",
    severity: "low",
    problem: "Dining in wrong zone causes digestive issues and family conflicts during meals",
    scientificReason:
      "West-facing dining aligns with evening energy suitable for family meals. SE (fire zone) causes over-eating or digestive fire imbalance",
    traditionalReason:
      "West is Varuna zone governing water and sustenance. Dining here ensures nourishment and family bonding",
    remedy: {
      easy: "Place dining table in West or East zone. Avoid sitting with back to entrance while eating.",
      moderate: "Add yellow or orange accent lights over dining table.",
      color: "Warm colors (yellow, orange) for dining area enhance appetite and family bonding",
      element: "earth",
      plants: "Fresh flowers on dining table attract abundance",
      crystals: "Citrine or sunstone for positive meal energy",
    },
    expectedImprovement: "Better digestion, family harmony during meals, abundance mindset",
    confidenceScore: 75,
  },
  {
    id: "tv_primary",
    object: "tv",
    objectLabel: "TV / Entertainment Unit / Screen",
    idealZones: ["ENE", "NW"],
    beneficialZones: [],
    remedyZones: [],
    strictNoZones: ["NE", "SSW"],
    room: "living_room",
    severity: "medium",
    problem: "TV in NE zone causes major distraction, reduces clarity, and blocks meditation energy",
    scientificReason:
      "TV emits EMF radiation — NE is most sensitive zone for brain activity. TV here disrupts mental clarity and spiritual development",
    traditionalReason:
      "NE is clarity/mind zone — electronic disturbances here block divine signals and mental peace",
    remedy: {
      easy: "Move TV to ENE or NW wall. Keep TV cabinet closed when not in use.",
      moderate: "Place Tulsi plant near TV to absorb EMF radiation.",
      color: "Neutral colors (grey, brown) for TV unit",
      element: "space",
      plants: "Spider plant or peace lily absorbs EMF near electronics",
      crystals: "Black tourmaline to absorb electronic radiation",
    },
    expectedImprovement: "Better mental clarity, reduced screen addiction, improved family communication",
    confidenceScore: 82,
  },
  {
    id: "guest_bedroom_primary",
    object: "guest_bedroom",
    objectLabel: "Guest Bedroom / Spare Room",
    idealZones: [],
    beneficialZones: [],
    remedyZones: ["SW", "NE"],
    remedyDescription: "SW causes guests to overstay, NE is not ideal",
    strictNoZones: [],
    room: "bedroom",
    severity: "low",
    problem: "Guest bedroom placement affects how long guests stay and the energy they bring",
    scientificReason: "NW is movement zone — guests in NW naturally want to leave after appropriate stay",
    traditionalReason:
      "NW is Vayu zone governing movement and transience — ideal for guests",
    remedy: {
      easy: "Assign NW room for guests. Use light, airy decor.",
      moderate: "Avoid SW bedroom for guests as it gives them authority/dominance energy.",
      color: "Light colors (white, cream, light yellow) for guest room",
      element: "air",
      plants: "Light fragrant plants like lavender",
      crystals: "None specific",
    },
    expectedImprovement: "Guests stay appropriate duration, positive guest experiences",
    confidenceScore: 72,
  },
  {
    id: "mirror_primary",
    object: "mirror",
    objectLabel: "Mirror / Dressing Table / Vanity",
    idealZones: ["North", "East"],
    beneficialZones: ["NNE", "NE"],
    remedyZones: [],
    remedyDescription: "Never place mirror reflecting the bed",
    strictNoZones: ["South", "SE", "SW", "SSW"],
    room: "bedroom",
    severity: "high",
    problem:
      "Mirror in wrong direction or reflecting bed causes sleep disturbances, health issues, and relationship problems",
    scientificReason:
      "Mirrors reflecting beds disturb REM sleep cycles by creating psychological alertness. South-facing mirrors reflect and amplify heat energy",
    traditionalReason:
      "Mirror reflecting bed doubles illness and marital discord per Vastu — it is considered highly inauspicious",
    remedy: {
      easy: "Cover mirror at night if it reflects bed. Move mirror to North or East wall.",
      moderate: "Install sliding panel over mirror in bedroom.",
      color: "Silver or gold frame for mirrors — avoid black frames",
      element: "water",
      plants: "None specific",
      crystals: "None near mirrors",
    },
    expectedImprovement: "Better sleep quality, improved health, relationship harmony",
    confidenceScore: 90,
  },
  {
    id: "plants_primary",
    object: "plants",
    objectLabel: "Plants / Indoor Pots / Garden",
    idealZones: ["East", "ENE", "North"],
    beneficialZones: ["SE"],
    remedyZones: [],
    remedyDescription: "SE only for red flowers",
    strictNoZones: ["SW", "SSW", "WNW", "West"],
    room: "any",
    severity: "low",
    problem: "Plants in SW or West zones drain earth element and reduce stability",
    scientificReason:
      "East-facing plants receive morning photosynthesis energy producing maximum oxygen. SW plants compete with earth element causing instability",
    traditionalReason: "East and North are growth zones per Vastu — plants here amplify prosperity and vitality",
    remedy: {
      easy: "Move plants to East, ENE, or North zones. Remove plants from SW/West.",
      moderate: "Use Tulsi in NE for spiritual purification.",
      color: "Green plants for North (wealth), flowering plants for East (health)",
      element: "wood",
      plants: "Tulsi (NE), Money plant (North), Bamboo (East), Peace lily (ENE)",
      crystals: "Green aventurine near plants for growth",
    },
    expectedImprovement: "Improved air quality, prosperity, health, and positive energy flow",
    confidenceScore: 78,
  },
  {
    id: "heavy_storage_primary",
    object: "heavy_storage",
    objectLabel: "Heavy Storage / Almirah / Junk Room",
    idealZones: ["SW", "West"],
    beneficialZones: [],
    remedyZones: [],
    strictNoZones: ["NE", "North", "East"],
    room: "any",
    severity: "high",
    problem: "Heavy storage in NE or North blocks energy flow, mental clarity, and career opportunities",
    scientificReason:
      "NE and North need to be light and open for energy circulation. Heavy mass here creates stagnation in career and mental zones",
    traditionalReason:
      "SW is earth element zone — heavy objects here strengthen foundation and stability. NE with heavy objects suffocates clarity zone",
    remedy: {
      easy: "Move heavy almirahs, storage boxes to SW or West. Declutter NE immediately.",
      moderate: "Place heavy furniture against SW wall of any room.",
      color: "Earth tones (brown, dark grey) for storage areas",
      element: "earth",
      plants: "None in storage areas",
      crystals: "None specific",
    },
    expectedImprovement: "Mental clarity improves, career opportunities increase, North-East energy activated",
    confidenceScore: 87,
  },
];

export const ZONE_ACTIVATION_GUIDE: Record<string, ZoneActivationInfo> = {
  N: {
    fullName: "North",
    deity: "Mukhya, Bhallat, Soma",
    element: "Water",
    color: "Blue, Black",
    purpose: "Money & Opportunities",
    bestFor: ["Kuber brass idol", "Cash counting machine painting", "Blue water painting", "Blue crystals/vase"],
    avoid: ["Fire elements", "Red colors", "Heavy storage"],
    affirmation: "Wealth and opportunities flow freely to me",
  },
  NNE: {
    fullName: "North-North-East",
    deity: "Bhujag, Aditi, Diti",
    element: "Water",
    color: "Blue, White",
    purpose: "Health & Healing",
    bestFor: ["Medicine box", "Dhanvantari brass idol", "White lotus painting", "Healing crystals"],
    avoid: ["Fire elements", "Dark colors", "Clutter"],
    affirmation: "Perfect health and healing energy flows through my home",
  },
  NE: {
    fullName: "North-East",
    deity: "Shikhi, Parjanya",
    element: "Water",
    color: "Light Blue, White",
    purpose: "Clarity & Mind",
    bestFor: ["Temple/puja", "Silver Nandi", "Clear quartz", "Water feature"],
    avoid: ["Toilet", "Kitchen", "Heavy storage", "Bedroom", "TV"],
    affirmation: "Divine clarity and wisdom guide all my decisions",
  },
  ENE: {
    fullName: "East-North-East",
    deity: "Jayanta, Mahendra",
    element: "Air/Wood",
    color: "Light Green, White",
    purpose: "Success & Achievement",
    bestFor: ["TV", "Study area", "Plants", "Achievement symbols"],
    avoid: ["Toilets", "Heavy junk"],
    affirmation: "Success and achievements multiply in my life",
  },
  E: {
    fullName: "East",
    deity: "Surya",
    element: "Air/Wood",
    color: "White, Light Yellow",
    purpose: "Social Connections & Growth",
    bestFor: ["Main entrance if possible", "Study table facing East", "Plants", "Sunrise paintings"],
    avoid: ["Heavy storage", "Dark colors"],
    affirmation: "Positive social connections and growth surround me",
  },
  ESE: {
    fullName: "East-South-East",
    deity: "Aryama, Savita",
    element: "Air/Fire",
    color: "White, Silver",
    purpose: "Education & Skill",
    bestFor: ["Study materials", "Books", "Washing machine (utility)"],
    avoid: ["Bedroom", "Toilet"],
    affirmation: "Knowledge and skills flow effortlessly to me",
  },
  SE: {
    fullName: "South-East",
    deity: "Anil, Vitatha",
    element: "Fire",
    color: "Orange, Red, Pink",
    purpose: "Cash Flow & Energy",
    bestFor: ["Kitchen/hob", "Inverter", "Fire-related items", "Red flower plants"],
    avoid: ["Water features", "Blue colors", "Bedroom"],
    affirmation: "Cash flow and energy are abundant in my life",
  },
  SSE: {
    fullName: "South-South-East",
    deity: "Pusha, Vitatha",
    element: "Fire",
    color: "Orange, Red",
    purpose: "Confidence & Strength",
    bestFor: ["Kitchen", "Fire elements", "Red accents"],
    avoid: ["Water features", "Bedroom"],
    affirmation: "Confidence and strength guide my every action",
  },
  S: {
    fullName: "South",
    deity: "Yama",
    element: "Earth",
    color: "Red, Pink, Orange",
    purpose: "Fame & Recognition",
    bestFor: ["Fame/recognition symbols", "Red paintings", "Awards display"],
    avoid: ["Main entrance", "Water features"],
    affirmation: "Fame and recognition come naturally to me",
  },
  SSW: {
    fullName: "South-South-West",
    deity: "Grihakshat, Gandharva",
    element: "Earth",
    color: "Yellow, Brown",
    purpose: "Disposal & Waste Management",
    bestFor: ["Toilet", "Dustbin (if necessary)", "Waste areas"],
    avoid: ["Temple", "Main entrance", "Bedroom"],
    affirmation: "All negativity and waste naturally leaves my space",
  },
  SW: {
    fullName: "South-West",
    deity: "Nairuti",
    element: "Earth",
    color: "Brown, Beige, Earthy",
    purpose: "Stability & Relationships",
    bestFor: ["Master bedroom", "Heavy storage", "Safe (for retention)"],
    avoid: ["Main entrance", "Temple", "Kitchen"],
    affirmation: "Stability, security, and strong relationships define my life",
  },
  WSW: {
    fullName: "West-South-West",
    deity: "Dauvarik, Sugreeva",
    element: "Earth",
    color: "Yellow, Brown",
    purpose: "Education & Profits",
    bestFor: ["Study table", "Education materials", "Financial records"],
    avoid: ["Toilet", "Kitchen"],
    affirmation: "Education and profits multiply consistently",
  },
  W: {
    fullName: "West",
    deity: "Varuna",
    element: "Metal/Space",
    color: "Blue, White, Silver",
    purpose: "Gains & Profits",
    bestFor: ["Dining table", "Gains-related activities", "Safe", "Children bedroom"],
    avoid: ["Main entrance (generally)"],
    affirmation: "Gains and profits flow steadily into my life",
  },
  WNW: {
    fullName: "West-North-West",
    deity: "Roga, Vayu",
    element: "Air",
    color: "Grey, White",
    purpose: "Movement & Banking",
    bestFor: ["Washing machine", "Movement-related items", "Bank documents"],
    avoid: ["Main entrance", "Temple", "Master bedroom"],
    affirmation: "Positive movement and banking energy support my growth",
  },
  NW: {
    fullName: "North-West",
    deity: "Naga, Mukhya",
    element: "Air",
    color: "White, Silver, Grey",
    purpose: "Support & Networking",
    bestFor: ["Guest bedroom", "Washing machine", "Support from others", "TV (secondary)"],
    avoid: ["Master bedroom", "Main entrance"],
    affirmation: "Powerful support and network connections surround me",
  },
  NNW: {
    fullName: "North-North-West",
    deity: "Mukhya, Bhallat",
    element: "Air/Water",
    color: "White, Blue",
    purpose: "Attraction & Charm",
    bestFor: ["Bedroom for single people", "Attraction symbols", "Social area"],
    avoid: ["Heavy storage", "Waste areas"],
    affirmation: "I attract positive people and opportunities effortlessly",
  },
};

export const VASTU_OBJECTS_COVERED = [
  ...new Set(VASTU_RULES.map((r) => r.object)),
];

export function getVastuRulesCount(): number {
  return VASTU_RULES.length;
}
