import type { Metadata } from "next";

import { getTenant } from "@/lib/tenants";

const tenant = getTenant();
const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ?? `https://${tenant.domain}`;
const kundliTitle = `Free Kundli | ${tenant.name} — Accurate Vedic Birth Chart`;

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: kundliTitle,
  description:
    "Get your free Kundli online. Most accurate Vedic birth chart with Swiss Ephemeris precision. Planet positions, Dasha periods, Mangal Dosha, Yogas, and detailed predictions.",
  keywords: [
    "free kundli",
    "janam kundli",
    "birth chart",
    "vedic astrology",
    "kundali online",
  ],
  openGraph: {
    title: kundliTitle,
    description:
      "Most accurate Vedic birth chart with Swiss Ephemeris precision — planets, Dasha, Doshas & Yogas.",
    type: "website",
    locale: "en_IN",
    siteName: tenant.name,
    /* OG image: generated by ./opengraph-image.tsx (1200×630) */
    images: [
      {
        url: "/kundli/opengraph-image",
        width: 1200,
        height: 630,
        alt: `${tenant.name} — Free Vedic Kundli`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `Free Kundli | ${tenant.name}`,
    description:
      "Accurate Vedic birth chart — Swiss Ephemeris precision. Planets, Dasha, Doshas & more.",
  },
};

export default function KundliLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
